---
# https://github.com/kelseyhightower/confd/blob/master/docs/installation.md
# https://gist.github.com/warmfusion/b91dd15badcf37d072b8180feb740e91
- name: confd 
  hosts: vbox01
  become: yes
  become_user: root
  become_method: su
  gather_facts: no

  vars_files:
    - ~/vault.yaml
    - ~/internal.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"
    - confdurl: https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64

  
  tasks:
  - name: rmold confd
    file:
      path: /usr/local/bin/confd
      state: absent

  - name: get confd
    get_url:
      url: "{{ confdurl }}"
      dest: /usr/local/bin/confd
      owner: root
      group: root
      mode: 0755
  
  - name: test confd
    command: "/usr/local/bin/confd --version"
    register: confd
    tags: confdtest
  - debug:
      var: confd.stdout_lines
    tags: confdtest
  
  - name: setup config dir
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /etc/confd/conf.d
      - /etc/confd/templates
    tags:
      - post

  - name: toml files
    copy:
      src: "./files/{{ item }}"
      dest: /etc/confd/conf.d/
    with_items:
      - confd-haapp.toml
    tags:
      - post

  - name: tmpl files
    copy:
      src: "./files/{{ item }}"
      dest: /etc/confd/templates/
    with_items:
      - confd-haapp.conf.tmpl
    tags:
      - post

  - name: confd systemd
    copy:
      src: confd.service
      dest: /etc/systemd/system/confd.service
    tags: 
      - post
  - systemd:
       name: confd
       enabled: yes
       state: stopped
    tags: 
      - post

