---
# docker install centos
- name: docker
  become_user: root
  become_method: sudo
  become: yes
  hosts: vbox01

  vars_files:
    - ~/vault.yaml
  
  vars:
    ansible_ssh_pass: "{{ root_remote }}"

  tasks:
    - name: install prereqs
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - device-mapper-persistent-data
        - lvm2
    
    - name: install repo
      command: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'

    - name: install docker
      yum:
        name: "{{ items }}"
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io