---
# docker install centos
- name: docker
  become_user: root
  become_method: sudo
  become: no
  hosts: vbox01

  vars_files:
    - ~/vault.yaml
  
  vars:
    ansible_ssh_pass: "{{ root_remote }}"

  tasks:
    - name: install prereqs
      yum:
        name: ['device-mapper-persistent-data', 'lvm2']
        state: present
    
    - name: install repo
      command: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'

    - name: install docker
      yum:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present

