---
# docker install centos
- name: docker
  hosts: swarm
  become_user: root
  become_method: sudo
  become: yes

  vars_files:
    - ~/vault.yaml
  
  vars:
    ansible_ssh_pass: "{{ root_remote }}"
    composeurl: https://github.com/docker/compose/releases/download/1.24.1
    dockerurl: http://10.10.10.10/custom/docker

  tasks:
    - name: patch
      yum:
        name: '*'
        state: latest
        exclude: kernel*
      tags: update

    - name: install prereqs
      yum:
        name: ['device-mapper-persistent-data', 'lvm2']
        state: present
      tags: dockerint

    - name: install repo
      command: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'
     
    - name: install docker
      yum:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present

    - name: install docker private
      yum:
        name: 
          - "{{ dockerurl }}/docker-ce-19.03.1-3.el7.x86_64.rpm"
          - "{{ dockerurl }}/docker-ce-cli-19.03.1-3.el7.x86_64.rpm"
          - "{{ dockerurl }}/containerd.io-1.2.6-3.3.el7.x86_64.rpm"
        state: present
      tags: ['never', 'dockerint']
  
    - name: docker compose
      get_url:
        url:  "{{ composeurl }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 0755
      tags:
        - compose
  
    - name: firewall overlay
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 2377/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/udp
      tags: ['never', 'swarm']

    - name: docker-machine
      get_url:
        url: "https://github.com/docker/machine/releases/download/v0.16.0/ocker-machine-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
        dest: /usr/local/bin/docker-machine
        owner: root
        group: root 
        mode: 0755
      tags: ['never', 'machine']

    - name: docker start
      systemd:
        name: docker
        enabled: yes
        state: restarted
        

