---
# Setup for running Azure Pipeline Agent for Linux
#
# https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/start/envlinux.md
# https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
- name: dotnet core
  hosts: swarm
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - ~/vault.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"
  
  tasks:
    - name: dotnet product feed
      yum:
        name: https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
        state: present

    - name: prereqs
      yum:
        name: ['lttng-ust', 'libcurl', 'openssl-libs', 'krb5-libs', 'libicu', 'zlib']
        state: present
    
    - name: dotnet sdk
      yum:
        name: dotnet-sdk-2.2
        state: present

    - name: azure agent user
      group:
        name: azagent
        gid: 1020
        state: present
      tags:
        - post
    - user:
        name: azagent
        comment: azagent
        uid: 1020
        group: azagent
        home: /home/azagent
        shell: /sbin/nologin
      tags: 
       - post
      
      