---
- hosts: swarm
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: stop swarm
      systemd:
        name: docker.service
        state: stopped
      ignore_errors: true

    - name: shutdown
      command: /sbin/shutdown -h now
      async: 1
      poll: 0

    - name: restart swarm
      systemd:
        name: docker.service
        state: restarted
      tags:
        - restart
#    - name: wait go down
#      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped
