---
- name: firewalld
  hosts: swarm
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: firewall swarm jenkins
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 2376/tcp
        - 2377/tcp
        - 2379/tcp
        - 2380/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/udp
        - 9000/tcp
        - 8080/tcp
        - 443/tcp
        - 80/tcp
 
    - name: restart
      systemd: 
        name: firewalld
        state: restarted

    - name: stop
      systemd:
        name: firewalld
        state: stopped
      tags: ['never','stop']
