---
# Presuppose docker.yml
# https://ralph.blog.imixs.com/2019/11/17/from-docker-swarm-to-kubernetes-in-the-easy-way/
- name: kubernetes
  hosts: swarm
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - ~/vault.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"

  tasks:
    - name: K8s Repo 
      copy: 
        src: ./files/kubernetes.repo 
        dest: /etc/yum.repos.d/kubernetes.repo 
        mode: 0644

    - name: install k8s 
      yum:
        name: kubelet
        state: present
    - yum:
        name: kubeadm
        state: present
    - yum:
        name: kubeadm
        state: present

    - name: docker driver repl
      copy:
        src: ./file/daemon.json
        dest: /etc/docker/daemon.json
    - systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon_reload: yes
        
#    - name: install helm
#      copy:
#        src: ./files/helm
#        dest: /usr/bin/helm
#        mode: '0755'
#      tags: helm
#  
#    - name: helm rancher repo 
#      command: /usr/bin/helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
#      tags: helm