---
- name: swarm
  hosts: swarm
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - ~/vault.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"

  tasks:
    # Create
    - name: create swarm
      docker_swarm:
        listen_addr: "{{ ansible_default_ipv4.address }}:2377"
        state: present
      register: token
      when: role is defined and role == "leader"
      tags: 
        - create
        - join

    - name: add workers
      docker_swarm:
        state: join
        advertise_addr: "{{ ansible_default_ipv4.address}}"
        join_token: "{{ hostvars['swarm1.owens.dev']['token']['swarm_facts']['JoinTokens']['Worker'] }}"
        remote_addrs: [ '10.3.234.100:2377' ]
      when: role is undefined        
      tags:
        - join
    
    - name: firewall trusted
      firewalld:
        zone: trusted
        interface: docker0
        permanent: yes
        state: enabled
      tags: fwd
    - firewalld:
        zone: trusted
        interface: docker_gwbridge
        permanent: yes
        state: enabled
      tags: fwd

