---
- hosts: swarm
  become: yes
  become_method: sudo
  become_user: root 

  vars_files:
    - ~/vault.yaml

  tasks:
    - name: Update
      yum:
        name: '*'
        state: latest
#        exclude: kernel*,teams*
