---
- name: test nginx content
  hosts: swarm
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - ~/vault.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"

  tasks:
    - name: volume dir
      file:
        path: /usr/share/www
        state: directory
        owner: root
        group: root 
        mode: 0755

    - name: index
      template:
        src: ./files/index.tmpl
        dest: /usr/share/www/index.html
        mode: 0444

    - name: create nginx service
      docker_swarm_service:
        name: test
        image: nginx
        networks:
          - traefik-net
        replicas: 1
        mounts:
          - source: /usr/share/www
            target: /usr/share/nginx/html
            type: bind
        labels:
          traefik.docker.network: "traefik-net"
          traefik.http.routers.test.entrypoints: "web"
          traefik.http.routers.test.rule: "Host(`test.owens.dev`)"
          traefik.http.routers.test.tls: "false"
          traefik.http.services.test.loadbalancer.server.port: "80"
      when: role is defined and role == "leader"
        
      
