---
# python rabbithole...
- name: dephole
  hosts: nodes
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - ~/vault.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"

  tasks:
    - name: epel pipold
      yum:
        name: epel-release
        state: installed
    - yum: 
        name: python2-pip
        state: installed

    - name: pip update
      shell: /usr/bin/pip install --upgrade pip

    - name: uninstall docker.py
      shell: /usr/bin/pip uninstall docker-py

    - name: install newest
      shell: /usr/bin/pip install docker --ignore-installed