---
- name: traefik
  hosts: swarm
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - ~/vault.yml

  vars:
    - ansible_ssh_user: "{{ me }}"

  tasks:
    - name: firewall overlay
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 80/tcp
        - 443/tcp
        - 8080/tcp
        - 9181/tcp

    - name: create cert and config directories
      file:
        path: /mnt/{{ item }}
        state: directory
        mode: '0755'
      with_items:
        - traefik-configs

    - name: create traefik-net networks
      docker_network:
        name: traefik-net
        driver: overlay
        attachable: yes
      when: role is defined and role == "leader"

    - name: create traefik swarm service
      docker_swarm_service:
        name: traefikv2
        image: traefik:v2.4.14
        networks:
          - traefik-net
        replicas: 1
        args: 
          # Enable API and Dashboard UI
          - "--api"
          - "--api.insecure=true"
          # Enable the Docker provider
          - "--providers.docker"
          - "--providers.docker.swarmmode=true"
          - "--providers.docker.watch"
          # Enable the File provider
          - "--providers.file.directory=/etc/traefik/dynamic"
          # Configure Entrypoints
          - "--entryPoints.web.address=:80"
          - "--entryPoints.websecure.address=:443"
          # Enable Prometheus metrics and logging
          - "--entryPoints.metrics.address=:9181"
          - "--metrics.prometheus"
          - "--metrics.prometheus.entryPoint=metrics"
          - "--log"
          - "--accessLog"
        publish:
          - published_port: 80
            target_port: 80
          - published_port: 443
            target_port: 443
          - published_port: 8080
            target_port: 8080
          - published_port: 9181
            target_port: 9181
        mounts:
          - source: /var/run/docker.sock
            target: /var/run/docker.sock
            type: bind
        placement:
          constraints:
            - node.role == manager
      when: role is defined and role == "leader"
