---
# Presuppose docker.yml
# https://ralph.blog.imixs.com/2019/11/17/from-docker-swarm-to-kubernetes-in-the-easy-way/
- name: kubernetes
  hosts: vbox1.owens.dev
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - ~/vault.yaml

  vars:
    - ansible_ssh_user: "{{ me }}"
# https://github.com/helm/helm/releases
    - helm: https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz

  tasks:
    - name: disable SELINUX
      selinux:
        state: disabled

# leftovers
    - name: iptables bridged traff
      sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
      with_items:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
      tags: ['never', 'checkifnecessary']

    - name: K8s Repo 
      copy: 
        src: ./files/kubernetes.repo 
        dest: /etc/yum.repos.d/kubernetes.repo 
        mode: 0644

    - name: install k8s 
      yum:
        name: ['kubelet', 'kubeadm', 'kubectl']
        state: present

    - name: enable kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: stopped
        daemon_reload: yes

    - name: docker driver repl
      copy:
        src: ./files/daemon.json
        dest: /etc/docker/daemon.json
      tags: dockerfix
    - systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon_reload: yes
      tags: dockerfix

    - name: install helm
      unarchive:
        src: "{{ helm }}"
        dest: /usr/local/bin
        mode: '0755'
        remote_src: yes
      tags: helm
    - file:
        src: /usr/local/bin/linux-amd64/helm
        dest: /usr/local/bin/helm
        state: link
      tags: helm
    - command: /usr/local/bin/helm repo add traefik https://helm.traefik.io/traefik
      tags: helm
    - command: /usr/local/bin/helm repo update
      tags: helm

    - name: helm rancher repo 
      command: /usr/bin/helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
      tags: ['never', 'helm']
