# https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md
[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
keys = [
    "/myapp/database/url",
    "/myapp/database/user",
]